/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Analytics {
  'totalBookings' : bigint,
  'occupiedSlots' : bigint,
  'availableSlots' : bigint,
}
export interface Booking {
  'id' : string,
  'startTime' : bigint,
  'status' : BookingStatus,
  'paymentStatus' : PaymentStatus,
  'endTime' : bigint,
  'userId' : Principal,
  'vehicleNumber' : string,
  'durationHours' : bigint,
  'slotId' : string,
  'qrCode' : string,
}
export type BookingStatus = { 'active' : null } |
  { 'cancelled' : null } |
  { 'completed' : null };
export interface ParkingSlot {
  'id' : string,
  'floor' : bigint,
  'status' : SlotStatus,
  'zone' : string,
  'pricePerHour' : number,
  'slotNumber' : string,
}
export type PaymentStatus = { 'pending' : null } |
  { 'paid' : null };
export type SlotStatus = { 'occupied' : null } |
  { 'booked' : null } |
  { 'available' : null };
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addSlot' : ActorMethod<[string, string, bigint, number], string>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'bookSlot' : ActorMethod<[string, string, bigint, bigint], Booking>,
  'cancelBooking' : ActorMethod<[string], undefined>,
  'confirmPayment' : ActorMethod<[string], undefined>,
  'getAllBookings' : ActorMethod<[], Array<Booking>>,
  'getAnalytics' : ActorMethod<[], Analytics>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getParkingSlots' : ActorMethod<[], Array<ParkingSlot>>,
  'getUserBookings' : ActorMethod<[], Array<Booking>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removeSlot' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateSlotStatus' : ActorMethod<[string, SlotStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];