/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BookingStatus = IDL.Variant({
  'active' : IDL.Null,
  'cancelled' : IDL.Null,
  'completed' : IDL.Null,
});
export const PaymentStatus = IDL.Variant({
  'pending' : IDL.Null,
  'paid' : IDL.Null,
});
export const Booking = IDL.Record({
  'id' : IDL.Text,
  'startTime' : IDL.Int,
  'status' : BookingStatus,
  'paymentStatus' : PaymentStatus,
  'endTime' : IDL.Int,
  'userId' : IDL.Principal,
  'vehicleNumber' : IDL.Text,
  'durationHours' : IDL.Nat,
  'slotId' : IDL.Text,
  'qrCode' : IDL.Text,
});
export const Analytics = IDL.Record({
  'totalBookings' : IDL.Nat,
  'occupiedSlots' : IDL.Nat,
  'availableSlots' : IDL.Nat,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const SlotStatus = IDL.Variant({
  'occupied' : IDL.Null,
  'booked' : IDL.Null,
  'available' : IDL.Null,
});
export const ParkingSlot = IDL.Record({
  'id' : IDL.Text,
  'floor' : IDL.Nat,
  'status' : SlotStatus,
  'zone' : IDL.Text,
  'pricePerHour' : IDL.Float64,
  'slotNumber' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addSlot' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Float64],
      [IDL.Text],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bookSlot' : IDL.Func([IDL.Text, IDL.Text, IDL.Int, IDL.Nat], [Booking], []),
  'cancelBooking' : IDL.Func([IDL.Text], [], []),
  'confirmPayment' : IDL.Func([IDL.Text], [], []),
  'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getAnalytics' : IDL.Func([], [Analytics], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getParkingSlots' : IDL.Func([], [IDL.Vec(ParkingSlot)], ['query']),
  'getUserBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeSlot' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateSlotStatus' : IDL.Func([IDL.Text, SlotStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BookingStatus = IDL.Variant({
    'active' : IDL.Null,
    'cancelled' : IDL.Null,
    'completed' : IDL.Null,
  });
  const PaymentStatus = IDL.Variant({
    'pending' : IDL.Null,
    'paid' : IDL.Null,
  });
  const Booking = IDL.Record({
    'id' : IDL.Text,
    'startTime' : IDL.Int,
    'status' : BookingStatus,
    'paymentStatus' : PaymentStatus,
    'endTime' : IDL.Int,
    'userId' : IDL.Principal,
    'vehicleNumber' : IDL.Text,
    'durationHours' : IDL.Nat,
    'slotId' : IDL.Text,
    'qrCode' : IDL.Text,
  });
  const Analytics = IDL.Record({
    'totalBookings' : IDL.Nat,
    'occupiedSlots' : IDL.Nat,
    'availableSlots' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const SlotStatus = IDL.Variant({
    'occupied' : IDL.Null,
    'booked' : IDL.Null,
    'available' : IDL.Null,
  });
  const ParkingSlot = IDL.Record({
    'id' : IDL.Text,
    'floor' : IDL.Nat,
    'status' : SlotStatus,
    'zone' : IDL.Text,
    'pricePerHour' : IDL.Float64,
    'slotNumber' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addSlot' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Float64],
        [IDL.Text],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bookSlot' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Int, IDL.Nat],
        [Booking],
        [],
      ),
    'cancelBooking' : IDL.Func([IDL.Text], [], []),
    'confirmPayment' : IDL.Func([IDL.Text], [], []),
    'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getAnalytics' : IDL.Func([], [Analytics], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getParkingSlots' : IDL.Func([], [IDL.Vec(ParkingSlot)], ['query']),
    'getUserBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeSlot' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateSlotStatus' : IDL.Func([IDL.Text, SlotStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };